-----------------------------
--PART A:
-----------------------------
--QUESTION 1:
---Show all active accounts whose account age (as of the retrieval date) is between 5 and 10 years or over 20 years
SELECT *
FROM Accounts
WHERE Account_Open_Date BETWEEN DATEADD(YEAR, 10, NOW()) AND DATEADD(YEAR, 5, NOW())
	OR Account_Open_Date < DATEADD(YEAR, 20, NOW())


--QUESTION 2:
---Display all accounts whose account age is less than the average account age. Withdrawals must include the account number and age of the account.
SELECT Account_ID, DATEDIFF(day, Account_Open_Date, NOW()) AS Age
FROM Accounts
WHERE Age <
	(
	SELECT AVERAGE(DATEDIFF(day, Account_Open_Date, NOW()))
	FROM Account
	WHERE YEAR(Account_Close_Date) <> '2999'
	)


--QUESTION 3:
---Display for each branch the following metrics:
--a.	Number of accounts in total
--b.	Number of business accounts
--c.	Number of private accounts
SELECT Brach_ID, COUNT(Account_Type) AS Total,
	SUM(CASE WHEN Account_Type=1  THEN 1
      WHEN Account_Type=2  THEN 0   
	END
	) AS Private,
	SUM(CASE WHEN Account_Type=2  THEN 1
      WHEN Account_Type=1  THEN 0   
	END
	) AS Business
FROM Accounts
WHERE YEAR(Account_Close_Date) <> '2999'
GROUP BY Brach_ID
HAVING Total > 10,000
ORDER BY Total DESC



--QUESTION 4:
---For each active (open) account, create a query that displays the following metrics:
--a.	The number of customers associated with the account
--b.	Number of customers with an
-------A-------
SELECT a.Account_ID, COUNT(acr.Customer_ID)
FROM Accounts a INNER JOIN Account_Customer_Relation acr
	ON a.Account_ID=acr.Account_ID
WHERE YEAR(a.Account_Close_Date) <> '2999'
	AND YEAR(acr.Relation_Close_Date) <> '2999'
GROUP BY a.Account_ID

-------B-------
SELECT a.Account_ID, COUNT(acr.Customer_ID)
FROM Accounts a INNER JOIN Account_Customer_Relation acr
	ON a.Account_ID=acr.Account_ID
WHERE YEAR(a.Account_Close_Date) <> '2999'
	AND YEAR(acr.Relation_Close_Date) <> '2999'
	AND Relation_Type_Code = 1
GROUP BY a.Account_ID

-----------------------------
--PART B:
-----------------------------
--Q1
---How many reports are expected in 2021?
SELECT COUNT(Report_Num)
FROM REPORT_TABLE
WHERE YEAR(Report_Date) = 2021

--Q2
---In 2021, how many reports are generated about a specific customer, including those that are segmented
SELECT f.First_ID, COUNT(r.Report_Num)
FROM REPORT_TABLE r INNER JOIN FIRST_ID f
	ON r.Customer_ID = f.Customer_ID
WHERE YEAR(r.Report_Date) = 2021
GROUP BY f.First_ID

--Q3
---In 2021, reporting reasons must be segmented
SELECT Report_Reason, COUNT(Report_Num)
FROM REPORT_TABLE
WHERE YEAR(Report_Date) = 2021
GROUP BY Report_Reason

--Q4
---What is the highest number of reports generated by a customer during 2021?
SELECT f.First_ID, COUNT(r.Report_Num)
FROM REPORT_TABLE r INNER JOIN FIRST_ID f
	ON r.Customer_ID = f.Customer_ID
WHERE YEAR(r.Report_Date) = 2021
GROUP BY f.First_ID
ORDER BY COUNT(r.Report_Num) DESC
limit 1





















